-- MySQL Script generated by MySQL Workbench
-- Thu Nov 17 21:38:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medical-center
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medical-center
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical-center` DEFAULT CHARACTER SET utf8 ;
USE `medical-center` ;

-- -----------------------------------------------------
-- Table `medical-center`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical-center`.`doctors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `spec` NVARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical-center`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical-center`.`patients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` NVARCHAR(45) NOT NULL,
  `name` NVARCHAR(45) NOT NULL,
  `email` NVARCHAR(255) NOT NULL,
  `gender` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical-center`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medical-center`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time_from` DATETIME NOT NULL,
  `time_to` DATETIME NOT NULL,
  `is_free` TINYINT NOT NULL,
  `type` INT NOT NULL,
  `doctors_id` INT NOT NULL,
  `patients_id` INT NOT NULL,
  PRIMARY KEY (`id`, `doctors_id`, `patients_id`),
  INDEX `fk_scheduler_doctors_idx` (`doctors_id` ASC) VISIBLE,
  INDEX `fk_scheduler_patients1_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `fk_scheduler_doctors`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `medical-center`.`doctors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_scheduler_patients1`
    FOREIGN KEY (`patients_id`)
    REFERENCES `medical-center`.`patients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
